---
title: "Final Project"
author: "Preston Scibek"
date: "May 13, 2018"
output: html_document
---

## Requirements
Summary
In lieu of a final exam, CMSC320 students will turn in a tutorial that will walk users through the entire data science pipeline: data curation, parsing, and management; exploratory data analysis; hypothesis testing and machine learning to provide analysis; and then the curation of a message or messages covering insights learned during the tutorial. Students may choose an application area and dataset(s) that are of interest to them; please feel free to be creative about this!

Remember, the course resources page has a number of data repositories from where you can download data. You could also create your own dataset using scraping skills you have learned in class. We in fact, encourage this.

The tutorial should be self-contained as an Rmarkdown document, and delivered as a GitHub statically-hosted Page (described below). You can see examples here: https://www.kaggle.com/kernels?sortBy=votes&group=everyone&pageSize=20&language=R

In general, the tutorial should contain at least 1500 words of prose and 150 lines of (nonpadded, legitimate) R code, along with appropriate documentation, visualization, and links to any external information that might help the reader.


Grading
We will assign a numeric score between 1 and 10 for each of the following six criteria:

Motivation. Does the tutorial make the reader believe the topic is relevant or important (i) in general and (ii) with respect to data science?
Understanding. After reading through the tutorial, does an uninformed reader feel informed about the topic? Would a reader who already knew about the topic feel like s/he learned more about it?
Other resources. Does the tutorial link out to other resources (on the web, in books, etc) that would give a lagging reader additional help on specific topics, or an advanced reader the ability to dive more deeply into a specific application area or technique?
Prose. Does the prose portion of the tutorial actually add to the content of the deliverable?
Code. Is the code well written, well documented, reproducible, and does it help the reader understand the tutorial? Does it give good examples of specific techniques?
Subjective evaluation. If somebody linked to this tutorial from, say, Hacker News, would people actually read through the entire thing?
The project is listed as 10% of the course grade in the syllabus. However, if you do exceptionally well in the final project (at least 55 of 60 points), we will count your final project as 20% of the grade (all other grades are downgraded uniformly) if that results in a better final course grade.

## Intro
url = https://baseballsavant.mlb.com/statcast_search?hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7C&hfC=&hfSea=2018%7C&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=&game_date_lt=&team=&position=&hfRO=&home_road=&batters_lookup%5B%5D=643217&batters_lookup%5B%5D=605141&batters_lookup%5B%5D=593428&batters_lookup%5B%5D=598265&batters_lookup%5B%5D=646240&batters_lookup%5B%5D=571788&batters_lookup%5B%5D=506702&batters_lookup%5B%5D=624407&batters_lookup%5B%5D=502110&batters_lookup%5B%5D=519048&batters_lookup%5B%5D=456488&batters_lookup%5B%5D=434670&batters_lookup%5B%5D=596119&batters_lookup%5B%5D=543877&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0#results

url = http://mlb.mlb.com/stats/sortable.jsp?c_id=bos#game_type='R'&season=2018&league_code='MLB'&split=&playerType=ALL&sectionType=sp&statType=hitting&elem=%5Bobject+Object%5D&tab_level=child&click_text=Sortable+Player+hitting&season_type=ANY&page=1&ts=1526240786294